builders:
  - docker
triggers:
  github_push: true  
  cron: "@daily"
clean_workspace: true

extra_jobs:  
  - name: docker-jenkins-java-job
    docker_name: sunet/docker-jenkins-java-job
    docker_file_dir: java
    
