builders:
  - multi-docker
triggers:
  github_push: true  
  cron: "@daily"
clean_workspace: true

multi-docker:
  default:
    name: docker-jenkins-job
    docker_name: sunet/docker-jenkins-job
    docker_file: Dockerfile
    
